openapi: 3.0.1
info:
  title: csvconvert
  description: API Definition of csvconvert
  version: 1.0.0
servers:
- url: http://localhost:8290/to-csv
paths:
  /:
    get:
      responses:
        default:
          description: Default response
    post:
      responses:
        default:
          description: Default response
